### ISSUE TITLE
scroll bar overlaps x axis

### ISSUE THREAD

**Issue by GregGoldman** [JimHokanson/interactive_matlab_plot#22]
when the figure is not full-screen, the scroll bar sometimes overlaps the axis

**Comment by JimHokanson** [comment]
Yeah I just saw this. Probably a bug I introduced while refactoring ...

**Comment by JimHokanson** [comment]
I'm not sure where you are seeing this ... I am seeing it when using a timer which can cause all sorts of havoc on the code. The bug is probably in: xLimChanged in the scroll bar code

**Comment by JimHokanson** [comment]
The code currently assumes that the xlim min and max don't change, but this is not necessarily true. If the min and max change then the scroll bar rendering is not correct.

**Comment by JimHokanson** [comment]
This is one of our first clear bugs. We should start introducing tests and make this one of them.

**Comment by JimHokanson** [comment]
I was misunderstanding this issue (a y-scale problem) with a bug that I was encountering (x_min and x_max of the axes not being accurate for calculating the scroll bar width)

For this issue I moved the scroll bar to the bottom of the figure. It looks fine now at most resolutions.
