### ISSUE TITLE
Add auto-scale x axis

### ISSUE THREAD

**Issue by GregGoldman** [JimHokanson/interactive_matlab_plot#23]

**Comment by JimHokanson** [comment]
I'm not sure if we want to have a button on the main screen for this, a toolbar entry, or some context menu on the scroll bar ...

**Comment by JimHokanson** [comment]
We can also add the ms,sec,min scaling in this

**Comment by JimHokanson** [comment]
Scaling of x-axis is complete. Holding off on changing units for now.
