### ISSUE TITLE
measure x and y

### ISSUE THREAD

**Issue by GregGoldman** [JimHokanson/interactive_matlab_plot#25]
Where should this info be displayed?

**Comment by JimHokanson** [comment]
I think any y-measurements should be displayed below the name if present.

Any x-lim measurement should be in the lower left corner (or below the y measurement)

The right panel needs to be refactored like the left-panel (i.e moving all positioning work in the main panel) with all callbacks in subclasses.

**Comment by JimHokanson** [comment]
the right panel has now been updated to have a better layout. Next we need to add a second text box for the y-measurement info

**Comment by JimHokanson** [comment]
y display is now in place, although there are some rendering issues with the lines and names that I am working out ...

**Comment by JimHokanson** [comment]
y is ok now, still need to work out x

**Comment by JimHokanson** [comment]
Both x and y now display
