### ISSUE TITLE
Remove dependencies

### ISSUE THREAD

**Issue by JimHokanson** [JimHokanson/interactive_matlab_plot#5]
All dependencies should be removed for general distribution.

**Comment by GregGoldman** [comment]
Do we have a processVarargin package which runs independently of the standard library?

**Comment by JimHokanson** [comment]
No. I typically will copy everything into the package under +sl

This will require copying a few files. I don't yet have a good dependency mover worked out :/

/+interactive_plot/+sl/

**Comment by JimHokanson** [comment]
It looks like this is "in progress" I uploaded a bug fix to make the code work.

**Comment by GregGoldman** [comment]
In progress. I'm going to look into a good way to move dependencies on the standard libarary for the general case

**Comment by JimHokanson** [comment]
This might be done. It still needs to be tested.
